// Define action types
export const FETCH_DONATIONS_REQUEST = 'FETCH_DONATIONS_REQUEST';
export const FETCH_DONATIONS_SUCCESS = 'FETCH_DONATIONS_SUCCESS';
export const FETCH_DONATIONS_FAILURE = 'FETCH_DONATIONS_FAILURE';


//Updation


export const UPDATE_DONATIONS_SUCCESS = 'UPDATE_DONATIONS_SUCCESS';

// Saving the donation data

export const SAVE_DONATION_DATA = 'SAVE_DONATION_DATA'; 
export const DELETE_SAVED_DONATION_DATA = 'DELETE_SAVED_DONATION_DATA'; 


