// Define action types
export const FETCH_DONATIONS_REQUEST = 'FETCH_DONATIONS_REQUEST';
export const FETCH_DONATIONS_SUCCESS = 'FETCH_DONATIONS_SUCCESS';
export const FETCH_DONATIONS_FAILURE = 'FETCH_DONATIONS_FAILURE';
