
export const ADMIN_REQUEST_ACTION = "ADMIN_REQUEST_ACTION" 
export const ADMIN_GET_SUCCESS = "ADMIN_GET_SUCCESS" 
export const ADMIN_GET_ALL_SUCCESS = "ADMIN_GET_ALL_SUCCESS" 
export const ADMIN_GET_ORG_SUCCESS = "ADMIN_GET_ORG_SUCCESS" 
export const ADMIN_FAILURE_ACTION = "ADMIN_FAILURE_ACTION" 