export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE";

export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';

export const GET_DONATED_DATA = 'GET_DONATED_DATA';
