export const AUTH_REQUEST = "AUTH_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const AUTH_FAILURE = "AUTH_FAILURE"

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
// export const ADMIN_REGISTER_SUCCESS = 'REGISTER_SUCCESS'
// export const ADMIN_LOGIN_SUCCESS = 'REGISTER_SUCCESS'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
